name: Build Template
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: rust-gh-example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo generate
        uses: cargo-generate/cargo-generate-action@v0.18.5
        with:
          name: ${{ env.PROJECT_NAME }}
          template: template
          arguments: "--define qualifier=com.github --define organization=oliverdding --define application=app"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo check
        # we need to move the generated project to a temp folder, away from the template project
        # otherwise `cargo` runs would fail
        # see https://github.com/rust-lang/cargo/issues/9922
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check --tests